### ISSUE TITLE
Ionic 2 RC 0 js does not export Ionic2RatingModule

### ISSUE THREAD

**Issue by danielehrhardt** [andrucz/ionic2-rating#2]
Hi i get this error:
![image](https://cloud.githubusercontent.com/assets/19570043/19017121/94fd173e-882f-11e6-8a9a-4e8452a1e882.png)

**Comment by Bubelbub** [comment]
Same here:

```
[23:53:42]  Error: Module C:\xampp\htdocs\node_modules\ionic2-rating\index.js does not export Ionic2RatingModule (imported by C:\xampp\htdocs\.tmp\app\app.module.js)
    at Module.trace (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:7677:29)
    at ModuleScope.findDeclaration (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:7300:22)
    at Scope.findDeclaration (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5351:39)
    at Identifier.bind (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:6489:29)
    at C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5151:50
    at ArrayExpression.eachChild (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5165:19)
    at ArrayExpression.bind (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5151:7)
    at C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5151:50
    at Node.eachChild (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5168:5)
    at Node.bind (C:\xampp\htdocs\node_modules\rollup\dist\rollup.js:5151:7)
```

package.json

```
  "dependencies": {
    "ionic2-rating": "0.0.8"
  },
```

**Comment by andrucz** [comment]
Hello guys. This is related to an ionic issue: https://github.com/driftyco/ionic/issues/8322

Please try the suggested workaround.

**Comment by andrucz** [comment]
I am closing this issue because of #3 
The workaround `import { Ionic2RatingModule } from 'ionic2-rating/module';` can be used until ionic issue is fixed.

**Comment by andrucz** [comment]
Just for your information: in version 0.0.10 no workaround is needed. We can simply do

``` TypeScript
import { Ionic2RatingModule } from 'ionic2-rating';
```
