### ISSUE TITLE
Error on Production Mode build

### ISSUE THREAD

**Issue by rizalio** [andrucz/ionic2-rating#24]
Hi I'm facing an error while using this package on production build.

Environtment:

```

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.2.1
    npm  : 5.3.0 
    OS   : Linux 4.10


```

The error says: 

```
Error: Template parse errors:
'rating' is not a known element:
1. If 'rating' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("orderData.status == "delivered"'>
		<p class="text-primary text-center">Rate Your Experience?</p>
		[ERROR ->]<rating style="font-size: 20px !important;" [(ngModel)]="rate" 
		        readOnly="false" 
		       "): ng:///home/rizal/ionic-project/biogreen-mobile/src/pages/order/order-details/order-details.html@43:2
[DEBUG] Error: Template parse errors:
        'rating' is not a known element:
        1. If 'rating' is an Angular component, then verify that it is part of this module.
        2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("orderData.status 
        == "delivered"'>
        		<p class="text-primary text-center">Rate Your Experience?</p>
        		[ERROR ->]<rating style="font-size: 20px !important;" [(ngModel)]="rate" 
        		        readOnly="false" 
        		       "): ng:///home/rizal/ionic-project/biogreen-mobile/src/pages/order/order-details/order-details.html@43:2
            at syntaxError 
        (/home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
            at TemplateParser.parse 
        (/home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:12041:19)
            at AotCompiler._compileComponent 
        (/home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:22867:39)
            at /home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:22764:55
            at Array.forEach (native)
            at AotCompiler._compileSrcFile 
        (/home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:22748:20)
            at /home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:22725:91
            at Array.map (native)
            at /home/rizal/ionic-project/biogreen-mobile/node_modules/@angular/compiler/bundles/compiler.umd.js:22725:56
            at <anonymous>

```

While I run `ionic cordova build android --prod` this produce error like above. But it run normally on `ionic cordova build android` (debug mode), FYI I'm new to Angular & Ionic, & I was looking on google about this issue but nothing usefull. Thanks!

**Comment by danielnbarros** [comment]
@rizalio I had the same error, but I don't know if it was the same cause. I just managed to get it working.
By any chance are you using Lazy Loading on the pages? If so, try to add the Ionic2RatingModule to the page module instead of the app module.

**Comment by andrucz** [comment]
Hello, @rizalio. Have you followed @danielnbarros instructions? Are you still facing the problem?

**Comment by Sampath-Lokuge** [comment]
Hope you need to add this to the `readme` doc since `lazy loading` is now the `default` on `Ionic 3` @andrucz

**Comment by andrucz** [comment]
@Sampath-Lokuge  I've just accepted a PR with a readme update regarding lazy loading.
