### ISSUE TITLE
ngc: Error: Unexpected value 'Ionic2RatingModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by chit786** [andrucz/ionic2-rating#4]
I am getting above error when trying to build the IOS package. ionic serve works but ionic build ios failed with below stacktrace : 

[22:21:14]  lint finished in 991 ms
[22:21:16]  ngc: Error: Unexpected value 'Ionic2RatingModule' imported by the module 'AppModule'
    at /Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler/bundles/compiler.umd.js:13982:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler/bundles/compiler.umd.js:13967:46)
    at /Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler/bundles/compiler.umd.js:12812:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler/bundles/compiler.umd.js:12811:21)
    at CodeGenerator.codegen (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler-cli/src/codegen.js:105:47)
    at codegen (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/chitrang/ionic2/CaffeIOT/node_modules/@angular/compiler-cli/src/main.js:14:9)

[22:21:16]  ngc: Compilation failed

[22:21:16]  ngc failed:  NGC encountered an error

[22:21:16]  Error: NGC encountered an error
    at ChildProcess.<anonymous> (/Users/chitrang/ionic2/CaffeIOT/node_modules/@ionic/app-scripts/dist/ngc.js:62:24)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error running ionic app script "build": Error: NGC encountered an error
..========================================================

app.module.ts snapshot: 
import { Ionic2RatingModule } from 'ionic2-rating/module';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    Orders,
    PlaceOrder,
    OrderDetail

  ],
  imports: [

```
IonicModule.forRoot(MyApp),
Ionic2RatingModule
```

  ],

Please advice.

**Comment by andrucz** [comment]
Take a look at this thread: https://forum.ionicframework.com/t/unexpected-value-ng2completermodule-imported-by-the-module-appmodule/65922/3

I will try to fix that problem as soon as I have free time to do it. If you can solve it, please submit a PR. Thanks!

**Comment by chit786** [comment]
@andrucz Thanks for reply.. I am surely going to have a deep look.

**Comment by grycroft** [comment]
Same problem.

**Comment by danielabbatt** [comment]
I have exactly the same issue when doing prod build. Seems to be related to rollup, Angular2 and aot? Affects both ios and Android build commands

**Comment by chit786** [comment]
@danielabbatt agreed issue is related to AOT. similar thread : https://github.com/telerik/kendo-angular2/issues/49

**Comment by chit786** [comment]
This issue is only specific to AOT compiler and JIT compiler ran this successfully and able to build.

**Comment by andrucz** [comment]
Please update to 0.0.9.

You might need to change module import from

```TypeScript
import { Ionic2RatingModule } from 'ionic2-rating/module';
```

to 

```TypeScript
import { Ionic2RatingModule } from 'ionic2-rating';
```

and edit node_modules/@ionic/app-scripts/config/rollup.config.js addind useStrict property and changing commonjs plugin declaration as the following example:

```JavaScript
module.exports = {
    useStrict: false,
    ...
    plugins: [
    ngTemplate(),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/ionic2-rating/**'
      ],
      namedExports: {
        'node_modules/ionic2-rating/index.js': ['Ionic2RatingModule']
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    })
  ]
}
```

**Comment by andrucz** [comment]
Please update to 0.0.10.
AoT compiler support was added and now we can do 

``` TypeScript
import { Ionic2RatingModule } from 'ionic2-rating';
```

without needing to edit rollup.config.js file.
